import React from 'react';
import ReactDOM from 'react-dom/client';
import VinLookup from './src/components/VinLookup';
import '/index.css';

const res = {
  "vin": "1HGCM82633A004352",
  "vehicle": {
    "make": "HONDA",
    "model": "Accord",
    "year": "2003",
    "body": "Coupe"
  },
  "parts": [
    {
      "Id": 74862,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02387GBNNALT",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit W/Sunroof",
      "WebsitePrice1_CanAm": "$93.58 ",
      "Availability": "In Stock",
      "Ships": "Immediately",
      "ShopPartPrice1_CanAm": "148.99",
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "92.55"
    },
    {
      "Id": 74861,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02387GBNN",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit W/Sunroof",
      "WebsitePrice1_CanAm": "$154.67 ",
      "Availability": "In Stock",
      "Ships": "Immediately",
      "ShopPartPrice1_CanAm": "148.99",
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "92.55"
    },
    {
      "Id": 74863,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02358GBNN",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit",
      "WebsitePrice1_CanAm": "Call for Price",
      "Availability": "-",
      "Ships": "-",
      "ShopPartPrice1_CanAm": null,
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "140.74"
    },
    {
      "Id": 74864,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02358GBYN",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit",
      "WebsitePrice1_CanAm": "Call for Price",
      "Availability": "-",
      "Ships": "-",
      "ShopPartPrice1_CanAm": null,
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "140.74"
    },
    {
      "Id": 74865,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02387GBNN",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit W/Sunroof",
      "WebsitePrice1_CanAm": "$154.67 ",
      "Availability": "In Stock",
      "Ships": "Immediately",
      "ShopPartPrice1_CanAm": "148.99",
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "92.55"
    },
    {
      "Id": 74866,
      "Year": 2003,
      "YearHref": "http://www.canamautoglass.ca/nags/2003",
      "Make": "Honda",
      "MakeHref": "http://www.canamautoglass.ca/nags/2003/HONDA",
      "Model": "Accord",
      "ModelHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324",
      "Body": "2 Door Coupe",
      "BodyHref": "http://www.canamautoglass.ca/nags/2003/HONDA/324/54853/",
      "PartNumber": "FW02387GBNNALT",
      "Description": "(Solar) (Green Tint / Blue Shade) W/Third Visor Frit W/Sunroof",
      "WebsitePrice1_CanAm": "$93.58 ",
      "Availability": "In Stock",
      "Ships": "Immediately",
      "ShopPartPrice1_CanAm": "148.99",
      "ShopPartPriceOveride": 0,
      "RainSensor": 0,
      "LaneDeparture": 0,
      "Acoustic": 0,
      "ElectrochromaticMirror": 0,
      "HeatedWiperPark": 0,
      "CondensationSensor": 0,
      "HeatedWindshield": 0,
      "HeadsupDispplay": 0,
      "ForwardCollisionAlert": 0,
      "Logo": 0,
      "HumiditySensor": 0,
      "ShopPriceList2_VanFax": null,
      "ShopPriceList3_Benson": null,
      "ShopPriceList4_PGW": "92.55"
    }
  ]
};
const vin = '1HGCM82633A004352';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <VinLookup initialState={{ vin, results: res }} />
  </React.StrictMode>
);